<?php
namespace mychaelstyle\queue;
require_once 'queue/Factory.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-23 at 08:26:53.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var Factory
   */
  protected $object;
  /**
   * @var string provider dsn
   */
  protected $dsn;
  /**
   * @var string provider connect options
   */
  protected $options = array();

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Factory;
    $this->dsn = 'AmazonSQS://'.$_SERVER['AWS_REGION_NAME'].'/tests';
    $this->options = array(
      'key' => $_SERVER['AWS_ACCESS_KEY'],
      'secret' => $_SERVER['AWS_SECRET_KEY'],
      'default_cache_config' => '',
      'certificate_autority' => false
    );
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }
  /**
   * @covers mychaelstyle\ProviderFactory::getProvider
   * @covers mychaelstyle\ProviderFactory::getClass
   * @covers mychaelstyle\ProviderFactory::perse
   * @covers mychaelstyle\queue\Factory::getPackage
   * @covers mychaelstyle\queue\Factory::getPath
   */
  public function testGetProvider(){
    
    $provider = $this->object->getProvider($this->dsn,$this->options);
    $this->assertEquals('mychaelstyle\\queue\\providers\AmazonSQS',get_class($provider));

  }
  /**
   * @covers mychaelstyle\ProviderFactory::getProvider
   * @covers mychaelstyle\ProviderFactory::getClass
   * @covers mychaelstyle\ProviderFactory::perse
   * @covers mychaelstyle\queue\Factory::getPackage
   * @covers mychaelstyle\queue\Factory::getPath
   * @expectedException mychaelstyle\Exception
   */
  public function testNoDsn(){
    $provider = $this->object->getProvider('',array());
  }
  /**
   * @covers mychaelstyle\ProviderFactory::getProvider
   * @covers mychaelstyle\ProviderFactory::getClass
   * @covers mychaelstyle\ProviderFactory::perse
   * @covers mychaelstyle\queue\Factory::getPackage
   * @covers mychaelstyle\queue\Factory::getPath
   * @expectedException mychaelstyle\Exception
   */
  public function testNoName(){
    $provider = $this->object->getProvider('://test',array());
  }
  /**
   * @covers mychaelstyle\ProviderFactory::getProvider
   * @covers mychaelstyle\ProviderFactory::getClass
   * @covers mychaelstyle\ProviderFactory::perse
   * @covers mychaelstyle\queue\Factory::getPackage
   * @covers mychaelstyle\queue\Factory::getPath
   * @expectedException mychaelstyle\Exception
   */
  public function testNoUri(){
    $provider = $this->object->getProvider('AmazonSQS://',array());
  }
  /**
   * @covers mychaelstyle\ProviderFactory::getProvider
   * @covers mychaelstyle\ProviderFactory::getClass
   * @covers mychaelstyle\ProviderFactory::perse
   * @covers mychaelstyle\queue\Factory::getPackage
   * @covers mychaelstyle\queue\Factory::getPath
   * @expectedException mychaelstyle\Exception
   */
  public function testNoNoClass(){
    $provider = $this->object->getProvider('AmazonTestS://TOKYO/tests',array());
  }

}
