<?php
namespace snb;
require_once 'Storage.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-10 at 18:46:21.
 */
class StorageTest extends \snb\TestBase
{
  /**
   * @var Storage
   */
  private $object;
  /**
   * dsn map
   */
  private $dsnMap = array();
  /**
   * test file uri
   */
  private $uri = 'test.txt';

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    parent::setUp();
    $this->dsnMap = array(
      'Local' => array(
        'dsn' => 'local:///Users/masanori/work/snb-php-utils/tests/work',
        'options' => array('permission'=>0644),
      ),
      'Local2' => array(
        'dsn' => 'local:///Users/masanori/work/snb-php-utils/tests/tmp',
        'options' => array('permission'=>0644),
      ),
      'AmazonS3' => array(
        'dsn' => 'amazon_s3://REGION_'.$_SERVER['SNB_AWS_S3_REGION_NAME'].'/'.$_SERVER['SNB_AWS_S3_BUCKET'],
        'options' => array(
          'key' => $_SERVER['SNB_AWS_KEY'],
          'secret' => $_SERVER['SNB_AWS_SECRET'],
          'default_cache_config' => '',
          'certificate_autority' => false
        )
      )
    );
    $def = $this->dsnMap['Local'];
    $this->object = new Storage($def['dsn'],$def['options'],false);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {
    parent::tearDown();
  }

  /**
   * file write
   * @covers snb\storage\File::open
   * @covers snb\storage\File::write
   * @covers snb\storage\File::close
   */
  protected function fileWrite($file,$strings){
    $file->open('w');
    $file->write($strings);
    $file->close();
    $file->commit();
  }

  /**
   * @covers snb\Storage::createFile
   * @covers snb\Storage::__construct
   * @covers snb\storage\File::__construct
   * @covers snb\storage\File::open
   * @covers snb\storage\File::write
   * @covers snb\storage\File::close
   */
  public function testCreateFile()
  {
    // renew storage
    $def = $this->dsnMap['Local'];
    $this->object = new Storage($def['dsn'],$def['options'],false);

    // create file
    $file = $this->object->createFile($this->uri_example);
    $this->assertNotNull($file);
    $this->assertEquals('snb\storage\File',get_class($file));
    // test writing
    $expected = 'This is test!';
    $this->fileWrite($file,$expected);
    $this->assertLocalWritten($def['dsn'],$expected,$this->uri_example);

    // remove file
    $this->object->remove($this->uri_example);
  }

  /**
   * @covers snb\Storage::addProvider
   * @covers snb\storage\File::__construct
   * @covers snb\storage\File::open
   * @covers snb\storage\File::write
   * @covers snb\storage\File::close
   */
  public function testAddProvider()
  {
    $def1 = $this->dsnMap['Local'];
    $def2 = $this->dsnMap['Local2'];
    $this->object->addProvider($def2['dsn'],$def2['options']);

    $file = $this->object->createFile($this->uri_example);

    $expected = 'This is test 2 providers!';
    $this->fileWrite($file,$expected);

    $this->assertLocalWritten($def1['dsn'],$expected,$this->uri_example);
    $this->assertLocalWritten($def2['dsn'],$expected,$this->uri_example);

    // remove file
    $this->object->remove($this->uri_example);

    // assertLocalDeleted
    $this->assertLocalDeleted($def1['dsn'],$this->uri_example);
    $this->assertLocalDeleted($def2['dsn'],$this->uri_example);
  }

  /**
   * @covers snb\Storage::removeProvider
   * @covers snb\Storage::addProvider
   * @covers snb\storage\File::__construct
   * @covers snb\storage\File::open
   * @covers snb\storage\File::write
   * @covers snb\storage\File::close
   * @depends testAddProvider
   */
  public function testRemoveProvider()
  {
    $def1 = $this->dsnMap['Local'];
    $def2 = $this->dsnMap['Local2'];
    $this->object->addProvider($def2['dsn'],$def2['options']);
    $this->object->removeProvider($def2['dsn'],$def2['options']);

    $file = $this->object->createFile($this->uri_example);

    $expected = 'This is test to remove provider!';
    $this->fileWrite($file,$expected);

    $this->assertLocalWritten($def1['dsn'],$expected,$this->uri_example);
    $this->assertLocalDeleted($def2['dsn'],$this->uri_example);

    // remove file
    $this->object->remove($this->uri_example);
    // assertLocalDeleted
    $this->assertLocalDeleted($def1['dsn'],$this->uri_example);
  }

  /**
   * @covers snb\Storage::put
   */
  public function testPut()
  {
    $def1 = $this->dsnMap['Local'];
    $def2 = $this->dsnMap['Local2'];
    $this->object->addProvider($def2['dsn'],$def2['options']);

    $path = DIR_TEST.'/fixtures/example.txt';
    $expected = file_get_contents($path);

    $this->object->put($path,$this->uri_example,array('permission'=>0644));
    
    $this->assertLocalWritten($def1['dsn'],$expected,$this->uri_example);
    $this->assertLocalWritten($def2['dsn'],$expected,$this->uri_example);

  }

  /**
   * @covers snb\Storage::get
   * @covers snb\Storage::put
   * @depends testPut
   */
  public function testGet()
  {
    $def1 = $this->dsnMap['Local'];
    $def2 = $this->dsnMap['Local2'];
    $this->object->addProvider($def2['dsn'],$def2['options']);

    $path = DIR_TEST.'/fixtures/example.txt';
    $expected = file_get_contents($path);

    $result = $this->object->get($this->uri_example);
    $this->assertEquals($expected,$result);
  }

  /**
   * @covers snb\Storage::remove
   * @covers snb\Storage::get
   * @covers snb\Storage::put
   * @depends testGet
   */
  public function testRemove()
  {
    $def1 = $this->dsnMap['Local'];
    $def2 = $this->dsnMap['Local2'];
    $this->object->addProvider($def2['dsn'],$def2['options']);
    // remove file
    $this->object->remove($this->uri_example);
    // assertLocalDeleted
    $this->assertLocalDeleted($def1['dsn'],$this->uri_example);
    $this->assertLocalDeleted($def2['dsn'],$this->uri_example);
  }

  /**
   * @covers snb\Storage::putContents
   */
  public function testPutContents()
  {
    $def1 = $this->dsnMap['Local'];
    $def2 = $this->dsnMap['Local2'];
    $this->object->addProvider($def2['dsn'],$def2['options']);

    $expected = 'This is put contents test';

    $this->object->putContents($this->uri_example,$expected,array('permission'=>0644));
    $result = $this->object->get($this->uri_example);
    $this->assertEquals($expected,$result);
  }

  /**
   * @covers snb\Storage::getContents
   * @depends testPutContents
   */
  public function testGetContents()
  {
    $def1 = $this->dsnMap['Local'];
    $def2 = $this->dsnMap['Local2'];
    $this->object->addProvider($def2['dsn'],$def2['options']);

    $expected = $this->getExampleContents();

    $result = $this->object->getContents($this->uri_example);
    $this->assertEquals($expected,$result);

    $this->testRemove();
  }

  /**
   * @covers snb\Storage::commit
   * @covers snb\storage\File::commit
   */
  public function testCommit()
  {
    $expected = $this->getExampleContents();
    $def = $this->dsnMap['Local'];
    $this->object = new Storage($def['dsn'],$def['options'],false);
    // file 1
    $path1 = $this->getLocalPathUsingUri($def['dsn'],$this->uri_example);
    if(file_exists($path1)){ @unlink($path1); }
    $file1 = $this->object->createFile($this->uri_example);
    $file1->putContents($expected);
    $this->assertFalse(file_exists($path1));
    // file 2
    $uri = '/test2/tmp.txt';
    $path2 = $this->getLocalPathUsingUri($def['dsn'],$uri);
    if(file_exists($path2)){ @unlink($path2); }
    $file2 = $this->object->createFile($uri);
    $file2->putContents($expected);
    $this->assertFalse(file_exists($path2));
    // commit
    $this->object->commit();
    $this->assertTrue(file_exists($path1));
    $this->assertTrue(file_exists($path2));
    $this->assertEquals($expected,file_get_contents($path1));
    $this->assertEquals($expected,file_get_contents($path2));

  }

  /**
   * @covers snb\Storage::rollback
   * @covers snb\storage\File::rollback
   */
  public function testRollback()
  {
    $expected = $this->getExampleContents();
    $def = $this->dsnMap['Local'];
    $this->object = new Storage($def['dsn'],$def['options'],false);
    // file 1
    $path1 = $this->getLocalPathUsingUri($def['dsn'],$this->uri_example);
    if(file_exists($path1)){ @unlink($path1); }
    $file1 = $this->object->createFile($this->uri_example);
    $file1->putContents($expected);
    $this->assertFalse(file_exists($path1));
    // file 2
    $uri = '/test2/tmp.txt';
    $path2 = $this->getLocalPathUsingUri($def['dsn'],$uri);
    if(file_exists($path2)){ @unlink($path2); }
    $file2 = $this->object->createFile($uri);
    $file2->putContents($expected);
    $this->assertFalse(file_exists($path2));
    // commit
    $this->object->rollback();
    $this->assertFalse(file_exists($path1));
    $this->assertFalse(file_exists($path2));

  }
}
