<?php
namespace snb;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-10 at 18:46:48.
 */
class TestBase extends \PHPUnit_Framework_TestCase
{
  /**
   * network
   */
  protected static $network = null;
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    parent::setUp();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    parent::tearDown();
  }

  /**
   * mark incomplete if no network
   */
  protected function markIncompleteIfNoNetwork(){
    if($this->hasAvailableNetwork()){
      return false;
    }
    $this->markTestIncomplete(
      'No available network now.'
    );
    return true;
  }
  /**
   * has available network
   */
  protected function hasAvailableNetwork(){
    if(is_null(self::$network)){
      $checkUrl = 'https://github.com/haruchaco/snb-php-utils';
      $result = $this->httpRequest($checkUrl);
      if('OK'==$result['result']){
        self::$network = true;
      } else {
        self::$network = false;
      }
    }
    return self::$network;
  }
  /**
   * encode contents
   * @param array $contentsMap contents key value map
   * @param string $encode 'json' / 'form', default 'form'
   */
  protected function encodeContents(array $contentsMap=array(), $encode='form'){
    if('json'==strtolower($encode)){
      return json_encode($contentsMap);
    } else {
      return http_build_query($contentsMap);
    }
  }
  /**
   * http request
   * @param string $url url
   * @param array $contentsMap
   * @param string $method
   * @param string $encode
   */
  protected function httpRequest($url,$contentsMap=null,$method='get',$encode='form'){

    $options = array(
      CURLOPT_RETURNTRANSFER => true,
      CURLOPT_HEADER         => true,
      CURLOPT_FOLLOWLOCATION => true,
      CURLOPT_ENCODING       => "",
      CURLOPT_USERAGENT      => 'SNB Test User Agent',
      CURLOPT_AUTOREFERER    => true,
      CURLOPT_CONNECTTIMEOUT => 10,
      CURLOPT_TIMEOUT        => 10,
      CURLOPT_MAXREDIRS      => 10,
      CURLOPT_URL            => $url,
      CURLOPT_SSL_VERIFYPEER => false,
    );

    $method = strtolower($method);
    $contents = is_null($contentsMap) ? null : $this->encodeContents($contentsMap, $encode);
    if('delete'==$method){
      $options[CURLOPT_DELETE] = true;
      $options[CURLOPT_POSTFIELDS] = $contents;
    } else if('put'==$method){
      $options[CURLOPT_PUT] = true;
      $options[CURLOPT_POSTFIELDS] = $contents;
    } else if('post'==$method){
      $options[CURLOPT_POST] = true;
      $options[CURLOPT_POSTFIELDS] = $contents;
    } else if(strlen($contents)>0) {
      $url = ((strpos($url,'?')===false) ? $url.'?' : $url.'&').$contents;
    }

    $ch = curl_init($url);
    curl_setopt_array($ch,$options);
    $content = curl_exec($ch);
    $info    = curl_getinfo($ch);
    $result  = array(
      'result'   => 'NG',
      'url'      => $url,
      'code'     => $info['http_code'],
      'errno'    => curl_errno($ch),
      'error'    => curl_error($ch),
      'info'     => $info,
      'headers'  => array(),
      'body'     => null
    );

    $msg = $method.' '.$url."\n".$contents."\n".print_r($info,true);
    if($content!==false){
      $result['result'] = 'OK';
      $header = substr($content,0,$info['header_size']);
      $body   = substr($content,$info['header_size']);
      $result['body'] = $body;
      $header = str_replace("\r\n","\n",$header);
      $header = str_replace("\r","\n",$header);
      $headerLines = explode("\n",$header);
      $headerMap = array();
      foreach($headerLines as $line){
        if(strpos($line,': ')!==false){
          list($key,$value) = explode(': ',$line);
          if(isset($headerMap[$key]) && is_scalar($headerMap[$key]) && strlen($headerMap[$key])>0){
            $headerMap[$key] = array($headerMap[$key],trim($line));
          } else if(isset($headerMap[$key]) && is_array($headerMap[$key])){
            $headerMap[$key][] = trim($line);
          } else {
            $headerMap[$key] = trim($line);
          }
        }
      }
      $result['headers'] = $headerMap;
    }
    return $result;
  }
}
