<?php
namespace mychaelstyle\storage;
require_once 'storage/Factory.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-10 at 18:47:19.
 */
class FactoryTest extends \mychaelstyle\TestBase
{
  /**
   * @var Provider
   */
  public $object;
  /**
   * @var array dsn map
   */
  private $dsnMap = array();
  /**
   * @var string example text
   */
  private $example_text;
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    parent::setUp();
    $this->dsnMap = array(
      'Local' => array(
        'dsn' => 'Local://'.DIR_WORK,
        'options' => array('permission'=>0644),
      ),
      'Local2' => array(
        'dsn' => 'Local://'.DIR_TMP,
        'options' => array('permission'=>0644),
      ),
      'AmazonS3' => array(
        'dsn' => 'AmazonS3://'.$_SERVER['AWS_REGION_NAME'].'/'.$_SERVER['AWS_S3_BUCKET'],
        'options' => array(
          'key' => $_SERVER['AWS_KEY'],
          'secret' => $_SERVER['AWS_SECRET'],
          'default_cache_config' => '',
          'certificate_autority' => false
        )
      )
    );
    $this->example_text = file_get_contents($this->org_example);
    $def = $this->dsnMap['Local'];
    $this->object = new \mychaelstyle\storage\Factory();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {
    parent::tearDown();
  }

  /**
   * @covers mychaelstyle\storage\Factory::getProvider
   * @covers mychaelstyle\ProviderFactory::getProvider
   * @covers mychaelstyle\storage\Factory::getPackage
   * @covers mychaelstyle\storage\Factory::getPath
   */
  public function testGetProvider()
  {
    $def = $this->dsnMap['Local'];
    // valid
    $provider = $this->object->getProvider($def['dsn'],$def['options']);
    $this->assertEquals('mychaelstyle\\storage\\providers\\Local',get_class($provider));
    // retry
    $provider = $this->object->getProvider($def['dsn'],$def['options']);
    $this->assertEquals('mychaelstyle\\storage\\providers\\Local',get_class($provider));
  }

  /**
   * @covers mychaelstyle\storage\Factory::getProvider
   * @covers mychaelstyle\ProviderFactory::getProvider
   * @covers mychaelstyle\storage\Factory::getPackage
   * @covers mychaelstyle\storage\Factory::getPath
   */
  public function testGetProviderException()
  {
    // invalid
    $def = $this->dsnMap['Local'];
    $this->setExpectedException('mychaelstyle\Exception');
    $provider = $this->object->getProvider('',$def['options']);
  }

}
