<?php
namespace mychaelstyle\utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-26 at 14:06:21.
 */
class FileTest extends \mychaelstyle\TestBase
{
  /**
   * @var File
   */
  protected $object;
  /**
   * @var string example text
   */
  private $example_text;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    parent::setUp();
    $this->object = new File;
    $this->example_text = file_get_contents($this->org_example);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }
  /**
   * @covers mychaelstyle\utils\File::encode
   * @covers mychaelstyle\utils\File::decode
   * @covers mychaelstyle\utils\File::base64
   */
  public function testEncode(){
    $expected = $this->example_text;
    $path   = $this->org_example;
    $to     = tempnam(DIR_TEST.'/tmp','encoded_');
    $recover  = tempnam(DIR_TEST.'/tmp','encoded_');
    \mychaelstyle\utils\File::base64encode($path,$to);
    \mychaelstyle\utils\File::base64decode($to,$recover);
    $this->assertEquals($expected,file_get_contents($recover));
    unlink($to);
    unlink($recover);
  }

}
