<?php
namespace mychaelstyle\utils;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-26 at 23:53:01.
 */
class StringTest extends \mychaelstyle\TestBase
{

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    parent::setUp();
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    parent::tearDown();
  }

  /**
   * @covers mychaelstyle\utils\String::getRandom
   */
  public function testGetRandom()
  {
    $result = String::getRandom();
    $this->assertEquals(16,strlen($result));

  }
}
