<?php
namespace mychaelstyle\datastore\providers;
require_once 'datastore/providers/Memcache.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-23 at 20:50:14.
 */
class MemcacheTest extends \mychaelstyle\TestBase
{
  /**
   * @var Memcache
   */
  protected $object;
  /**
   * @var string provider dsn
   */
  protected $dsn;
  /**
   * @var string $uri
   */
  protected $uri;
  /**
   * @var string provider connect options
   */
  protected $options = array();

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    parent::setUp();
    if(!class_exists('Memcached')){
      return;
    }
    $this->object = new Memcache;
    // set your aws key and secret to your env
    $this->uri = 'localhost:11211';
    $this->dsn = 'Memcache://'.$this->uri;
    $this->options = array(
      'prefix' => 'test_',
    );
    // curl options
    $this->object = new Memcache;
    $this->object->connect($this->uri,$this->options);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    parent::tearDown();
  }

  /**
   * @covers mychaelstyle\datastore\providers\Memcache::write
   * @covers mychaelstyle\datastore\providers\Memcache::batchWrite
   * @covers mychaelstyle\datastore\providers\Memcache::get
   * @covers mychaelstyle\datastore\providers\Memcache::batchGet
   * @covers mychaelstyle\datastore\providers\Memcache::connect
   */
  public function testFlow()
  {
    if(!class_exists('Memcached')){
      $this->markTestIncomplete(
        'PHP Memcached extension is not found!'
      );
    }
    $table = 'm_datastore';
    $t = time();
    $expected = array(
      $table => array(
        array(
          'id' => 'AAAA0001',
          'updated_at' => date('Y-m-d H:i:s'),
          'body' => 'This is test!',
        )
      )
    );
    $expectedKeys = array('id'=>'AAAA0001');

    // write
    $this->object->write($table,$expected[$table][0]);

    // get
    $result = $this->object->get($table,$expectedKeys);
    $this->assertEquals($expected[$table][0],$result);

    // remove
    $this->object->remove($table,$expectedKeys);
    $result = $this->object->get($table,$expectedKeys);
    $this->assertNull($result,print_r($result,true));

    // batch write
    $this->object->batchWrite($expected);

    // batchGet
    $result = $this->object->batchGet(
      array(
        $table=>array(
          $expectedKeys
        )
      )
    );
    $this->assertEquals($expected,$result);

    // batch remove
    $result = $this->object->batchRemove(
      array(
        $table=>array(
          $expectedKeys
        )
      )
    );
    $result = $this->object->get($table,$expectedKeys);
    $this->assertNull($result);
  }
}
