<?php
namespace snb\file;
require_once 'file/Exception.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-10 at 18:46:48.
 */
class ExceptionTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var Exception
   */
  public $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    $this->object = new Exception;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {
  }

  public function testThrow(){
    $this->setExpectedException('snb\file\Exception');
    throw $this->object;
  }
}
