<?php
namespace snb\file;
require_once 'file/File.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-10 at 18:46:39.
 */
class FileTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var File
   */
  public $object;
  /**
   * @var Strage
   */
  private $storage;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    $this->storage = new Storage('local:///Users/masanori_nakashima/work/snb-php-utils/tests');
    $this->object = new File($this->storage,'tmp.txt',array(),false);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {
  }

  /**
   * @covers snb\file\File::open
   * @todo   Implement testOpen().
   */
  public function testOpen()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\File::write
   * @todo   Implement testWrite().
   */
  public function testWrite()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\File::gets
   * @todo   Implement testGets().
   */
  public function testGets()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\File::eof
   * @todo   Implement testEof().
   */
  public function testEof()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\File::close
   * @todo   Implement testClose().
   */
  public function testClose()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\File::commit
   * @todo   Implement testCommit().
   */
  public function testCommit()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\File::rolback
   * @todo   Implement testRolback().
   */
  public function testRolback()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }
}
