<?php
namespace snb\file;
require_once 'file/Provider.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-10 at 18:47:19.
 */
class ProviderTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var Provider
   */
  public $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {
  }

  /**
   * @covers snb\file\Provider::getInstance
   * @todo   Implement testGetInstance().
   */
  public function testGetInstance()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }
}
