<?php
namespace snb\file;
require_once 'file/Storage.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-10 at 18:46:21.
 */
class StorageTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var Storage
   */
  private $object;

  private $dsnMap = array();

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    $this->dsnMap = array(
      'local:///Users/masanori/work/snb-php-utils/tests/work' => array('permission'=>0644),
    );
    $defaultDsn = array_shift(array_keys($this->dsnMap));
    $this->object = new Storage($defaultDsn,$this->dsnMap[$defaultDsn],false);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {
  }

  /**
   * @covers snb\file\Storage::createFile
   */
  public function testCreateFile()
  {
    $uri  = 'test.txt';
    $text = 'This is test!';
    $file = $this->object->createFile($uri);
    $this->assertNotNull($file);
    $this->assertEquals('snb\file\File',get_class($file));
    $file->open('w');
    $file->write($text);
    $file->close();
    $file->commit();
    $result = file_get_contents('/Users/masanori/work/snb-php-utils/tests/work/test.txt');
    $this->assertEquals($text,$result);
    $this->object->remove($uri);
  }

  /**
   * @covers snb\file\Storage::addProvider
   * @todo   Implement testAddProvider().
   */
  public function testAddProvider()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::removeProvider
   * @todo   Implement testRemoveProvider().
   */
  public function testRemoveProvider()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::put
   * @todo   Implement testPut().
   */
  public function testPut()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::get
   * @todo   Implement testGet().
   */
  public function testGet()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::remove
   * @todo   Implement testRemove().
   */
  public function testRemove()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::putContents
   * @todo   Implement testPutContents().
   */
  public function testPutContents()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::getContents
   * @todo   Implement testGetContents().
   */
  public function testGetContents()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::commit
   * @todo   Implement testCommit().
   */
  public function testCommit()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::rolback
   * @todo   Implement testRolback().
   */
  public function testRolback()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }
}
