<?php
namespace snb\file;
require_once 'file/Storage.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-10 at 18:46:21.
 */
class StorageTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var Storage
   */
  public $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  public function setUp()
  {
    $this->object = new Storage('local:///Users/masanori_nakashima/work/snb-php-utils/tests');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  public function tearDown()
  {
  }

  /**
   * @covers snb\file\Storage::createFile
   * @todo   Implement testCreateFile().
   */
  public function testCreateFile()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::addProvider
   * @todo   Implement testAddProvider().
   */
  public function testAddProvider()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::removeProvider
   * @todo   Implement testRemoveProvider().
   */
  public function testRemoveProvider()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::put
   * @todo   Implement testPut().
   */
  public function testPut()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::get
   * @todo   Implement testGet().
   */
  public function testGet()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::remove
   * @todo   Implement testRemove().
   */
  public function testRemove()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::putContents
   * @todo   Implement testPutContents().
   */
  public function testPutContents()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::getContents
   * @todo   Implement testGetContents().
   */
  public function testGetContents()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::commit
   * @todo   Implement testCommit().
   */
  public function testCommit()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers snb\file\Storage::rolback
   * @todo   Implement testRolback().
   */
  public function testRolback()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }
}
