<?php
namespace snb\queue;
require_once DIR_PROJECT.'/libs/queue/Factory.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-23 at 08:26:53.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var Factory
   */
  protected $object;
  /**
   * @var string provider dsn
   */
  protected $dsn;
  /**
   * @var string provider connect options
   */
  protected $options = array();

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Factory;
    require_once($_SERVER['SNB_AWS_PHPSDK']);
    // set your aws key and secret to your env
    $this->dsn = 'AmazonSQS://REGION_'.$_SERVER['SNB_AWS_S3_REGION_NAME'].'/tests';
    $this->options = array(
      'key' => $_SERVER['SNB_AWS_KEY'],
      'secret' => $_SERVER['SNB_AWS_SECRET'],
      'default_cache_config' => '',
      'certificate_autority' => false
    );
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
  }
  /**
   * @covers snb\ProviderFactory::getProvider
   * @covers snb\ProviderFactory::getClass
   * @covers snb\ProviderFactory::perse
   * @covers snb\queue\Factory::getPackage
   * @covers snb\queue\Factory::getPath
   */
  public function testGetProvider(){
    
    $provider = $this->object->getProvider($this->dsn,$this->options);
    $this->assertEquals('snb\\queue\\providers\AmazonSQS',get_class($provider));

  }
  /**
   * @covers snb\ProviderFactory::getProvider
   * @covers snb\ProviderFactory::getClass
   * @covers snb\ProviderFactory::perse
   * @covers snb\queue\Factory::getPackage
   * @covers snb\queue\Factory::getPath
   * @expectedException snb\Exception
   */
  public function testNoDsn(){
    $provider = $this->object->getProvider('',array());
  }
  /**
   * @covers snb\ProviderFactory::getProvider
   * @covers snb\ProviderFactory::getClass
   * @covers snb\ProviderFactory::perse
   * @covers snb\queue\Factory::getPackage
   * @covers snb\queue\Factory::getPath
   * @expectedException snb\Exception
   */
  public function testNoName(){
    $provider = $this->object->getProvider('://test',array());
  }
  /**
   * @covers snb\ProviderFactory::getProvider
   * @covers snb\ProviderFactory::getClass
   * @covers snb\ProviderFactory::perse
   * @covers snb\queue\Factory::getPackage
   * @covers snb\queue\Factory::getPath
   * @expectedException snb\Exception
   */
  public function testNoUri(){
    $provider = $this->object->getProvider('AmazonSQS://',array());
  }
  /**
   * @covers snb\ProviderFactory::getProvider
   * @covers snb\ProviderFactory::getClass
   * @covers snb\ProviderFactory::perse
   * @covers snb\queue\Factory::getPackage
   * @covers snb\queue\Factory::getPath
   * @expectedException snb\Exception
   */
  public function testNoNoClass(){
    $provider = $this->object->getProvider('AmazonTestS://TOKYO/tests',array());
  }

}
